src/objects/Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>SURQ-{00000000}</displayFormat>
        <label>Survey Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Survey_Question_Response__c.object
<CustomObject>
    <fields>
        <fullName>Boolean_Response__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Boolean Response</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <label>Survey Question</label>
        <referenceTo>Survey_Question__c</referenceTo>
        <relationshipLabel>Survey Responses</relationshipLabel>
        <relationshipName>Survey_Responsess</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Text_Response__c</fullName>
        <label>Text Response</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Survey Question Option</label>
    <nameField>
        <displayFormat>SURQR-{00000000}</displayFormat>
        <label>Survey Question Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Question Reponses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SurveyQuestionResponse.cls
public with sharing class SurveyQuestionResponse extends BaseModel {

    public static Finder find = new Finder('Survey_Question_Response__c');

    private SurveyQuestion mQuestion;

    public SurveyQuestionResponse() {
        this(new Survey_Question_Response__c());
    }

    public SurveyQuestionResponse(Survey_Question_Response__c response) {
        this(response, new SurveyQuestion(response.Survey_Question__r));
    }

    public SurveyQuestionResponse(Survey_Question_Response__c response, SurveyQuestion question) {
        super(response);
        mQuestion = question;
    }

    public Id getSurveyQuestionId() {
        return (Id)mObj.get('Survey_Question__c');
    }
    public void setSurveyQuestionId(Id surveyQuestion) {
        mObj.put('Survey_Question__c', surveyQuestion);
    }

    public Boolean getBooleanResponse() {
        return (Boolean)mObj.get('Boolean_Response__c');
    }
    public void setBooleanResponse(Boolean booleanResponse) {
        mObj.put('Boolean_Response__c', booleanResponse);
    }

    public String getTextResponse() {
        return (String)mObj.get('Text_Response__c');
    }
    public void setTextResponse(String textResponse) {
        mObj.put('Text_Response__c', textResponse);
    }

    public static List<SurveyQuestionResponse> decorate(List<sObject> questions) {
        List<SurveyQuestionResponse> result = new List<SurveyQuestionResponse>();
        for (Survey_Question_Response__c q : (List<Survey_Question_Response__c>)questions) {
            result.add(new SurveyQuestionResponse(q));
        }
        return result;
    }

    public class Finder extends BaseFinder {
        public Finder(String objectName) {
            super(objectName);
        }

        public List<SurveyQuestionResponse> byQuestion(String questionId) {
            return decorate(getSelectWhere('Question__c', questionId));
        }
    }
}