src/objects/Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>SURQ-{00000000}</displayFormat>
        <label>Survey Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey_Question_Option__c.object
<CustomObject>
    <fields>
        <fullName>Option__c</fullName>
        <label>Option</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <label>Survey Question</label>
        <referenceTo>Survey_Question__c</referenceTo>
        <relationshipLabel>Survey Options</relationshipLabel>
        <relationshipName>Survey_Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Question Option</label>
    <nameField>
        <displayFormat>SURQR-{00000000}</displayFormat>
        <label>Survey Question Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Question Reponses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SurveyQuestionOption.cls
public with sharing class SurveyQuestionOption extends BaseModel {

    public static Finder find = new Finder('Survey_Question_Option__c');

    public SurveyQuestionOption() {
        this(new Survey_Question_Option__c());
    }

    public SurveyQuestionOption(Survey_Question_Option__c option) {
        super(option);
    }

    public Id getSurveyQuestionId() {
        return (Id)mObj.get('Survey_Question__c');
    }
    public void setSurveyQuestionId(Id surveyQuestion) {
        mObj.put('Survey_Question__c', surveyQuestion);
    }

    public String getOption() {
        return (String)mObj.get('Option__c');
    }
    public void setOption(String option) {
        mObj.put('Option__c', option);
    }

    public static List<SurveyQuestionOption> decorate(List<sObject> questions) {
        List<SurveyQuestionOption> result = new List<SurveyQuestionOption>();
        for (Survey_Question_Option__c q : (List<Survey_Question_Option__c>)questions) {
            result.add(new SurveyQuestionOption(q));
        }
        return result;
    }

    public class Finder extends BaseFinder {
        public Finder(String objectName) {
            super(objectName);
        }

        public List<SurveyQuestionOption> byQuestion(String questionId) {
            return decorate(getSelectWhere('Question__c', questionId));
        }
    }
}