src/objects/Survey_Question__c.object
<CustomObject>
    <fields>
        <fullName>Question__c</fullName>
        <label>Question</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Survey Question</label>
    <nameField>
        <displayFormat>SURQ-{00000000}</displayFormat>
        <label>Survey Question Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Survey_Question_Option__c.object
<CustomObject>
    <fields>
        <fullName>Option__c</fullName>
        <label>Option</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Survey_Question__c</fullName>
        <label>Survey Question</label>
        <referenceTo>Survey_Question__c</referenceTo>
        <relationshipLabel>Survey Options</relationshipLabel>
        <relationshipName>Survey_Options</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Survey Question Option</label>
    <nameField>
        <displayFormat>SURQR-{00000000}</displayFormat>
        <label>Survey Question Option Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Question Reponses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SurveyQuestion.cls
public with sharing class SurveyQuestion {
    
    public static Finder find = new Finder('Survey_Question__c');

    public static final String TYPE_CHECKBOX = 'Checkbox';
    public static final String TYPE_PICKLIST = 'Picklist';
    public static final String TYPE_TEXT     = 'Text';


    public List<SurveyQuestionOption> options;
    private Boolean mIsCheckbox;
    private Boolean mIsText;
    private Boolean mIsPicklist;

    public SurveyQuestion() {
        this(new Survey_Question__c());
    }

    public SurveyQuestion(Survey_Question__c question) {
        super(question);
        options = SurveyQuestionOption.decorate(question.Survey_Options__r);
    }

    public String getQuestion() {
        return (String)mObj.get('Question__c');
    }
    public void setQuestion(String question) {
        mObj.put('Question__c', question);
    }

    public String getType() {
        return (String)mObj.get('Type__c');
    }
    public void setType(String type) {
        mObj.put('Type__c', type);
    }
    

    public Boolean getIsCheckbox() {
        if (mIsCheckbox == null) {
            setupTypeBooleans();
        }
        return mIsCheckbox;
    }

    public Boolean getIsPicklist() {
        if (mIsPicklist == null) {
            setupTypeBooleans();
        }
        return mIsPicklist;
    }

    public Boolean getIsText() {
        if (mIsText == null) {
            setupTypeBooleans();
        }
        return mIsText;
    }

    private void setupTypeBooleans() {
        mIsCheckbox = false;
        mIsText     = false;
        mIsPicklist = false;

        String type == getType();
        if (type == TYPE_CHECKBOX) {
            mIsCheckbox = true;
        }
        else if (type == TYPE_PICKLIST) {
            mIsPicklist = true;
        }
        else if (type == TYPE_TEXT) {
            mIsText = true;
        }

    }
    public static List<SurveyQuestion> decorate(List<sObject> questions) {
        List<SurveyQuestion> result = new List<SurveyQuestion>();
        for (sObject q : questions) {
            result.add(new SurveyQuestion(q));
        }
        return result;
    }

    public class Finder extends BaseFinder {
        public Finder(String objectName) {
            super(objectName);
            addFields(new Set<String>{
                '(SELECT Id, Option__c FROM Survey_Options__r)'
            });
        }

        public List<SurveyQuestion> all() {
            return decorate(getSelect());
        }
    }
}